### ISSUE TITLE
Version number inconsistency between repo and release

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-f2py#115]
It looks like the version number was messed in December. The repo has a version number and corresponding tag of 2022.08.0 but the conda-forge recipe, so the release was made with the version number 2022.04.0. 

We need to correct the version number (looks like it should be 2022.08.0) with January release.

**Comment by hCraker** [comment]
Hi @erogluorhan. The currently `metal.yaml` file has the correct version (2022.08.0) and the tag is correct. I'm not sure where the inconsistency is. I searched for "2022.04.0" in the this repo and in the feedstock repo and there were no results. I see that on Anaconda.org the version is listed as 2022.04.0. Do you have any idea what might be causing this? I can't find any inconsistencies in the tags or in the project files.

**Comment by erogluorhan** [comment]
The actual recipe that makes the releases happen is this: https://github.com/conda-forge/geocat-f2py-feedstock/blob/main/recipe/meta.yaml

and you can find 2022.04.0 in it. That is what needs to be fixed with the upcoming release.

The recipe you're referring to in the main -f2py repo is of no use for conda-forge releases, and actually @anissa111 had a plan to get rid of the that in the long run. You can talk to her on that

**Comment by hCraker** [comment]
Thanks for that info. I'll fix it this week
