### ISSUE TITLE
Naming convention: lat-lon or y-x?

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-f2py#29]
@michaelavs @anissa111 @pilotchute 

Do you have any preference between using "lat-lon" or "y, x" names for lat-lon variables throughout the code?

I am fine with either, but whatever the decision is, I think we should better be consistent with our use within every single function. Or should we just leave it to the individual developer's preference?

Thoughts?

**Comment by anissa111** [comment]
I think we should be consistent, too, and I have a slight preference for lat-lon, but would rather it be consistent if anybody has strong x-y preferences.

**Comment by michaelavs** [comment]
I agree with Anissa on keeping consistency with the variable names. I also have a preference for lat-lon, but if it is easier or preferred, using the x-y system would be completely fine to me!

**Comment by erogluorhan** [comment]
Thanks @anissa111 @michaelavs ! Looks like we have a consensus about consistency. Using "lat" and "lon" in Python makes sense to me as well since we are already referring to latitudes and longitudes even if we use "x" and "y"s for variables.

**Comment by michaelavs** [comment]
With regards to this decision, should I go back through rcm2points and update the yi/xi and yo/xo to their original lat/lon styles of lat2d/lon2d and lat1d/lon1d? Or will this be implemented going forward and not retroactively?

**Comment by pilotchute** [comment]
if the data format (RCM) for example, uses lat-lon, then use lat-lon. If the data format is not earth model specific (Linint2) for example, then x-y.

**Comment by erogluorhan** [comment]
> if the data format (RCM) for example, uses lat-lon, then use lat-lon. If the data format is not earth model specific (Linint2) for example, then x-y.

Agree with this, thanks!
