### ISSUE TITLE
Where to store ground truth data for unit tests

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-f2py#33]
The general workflow of writing unit tests for functions in this repo would most of the time involve writing a simple NCL script that generates simple input data and then produces output. We would then be using those inputs and outputs as ground truth (though there might always be a little possibility that NCL function is wrong instead; different story :) ) in our f2py unit tests. 

1. So, where should we keep those NCL scripts for future reference as well as tracking of where input-output test data came from? I don't think it should be kept anywhere in the repository; instead, but we should have them all together somewhere else.

2. Or, more broadly, please also speak out if you have an idea to generalizing/centralizing this unit testing data generation task. I mean, currently the unit tests of every single function generates its own data, but we may want to reduce also those type of code duplicates that are generating similar data of similar or the same dimensionality and contents.

**Comment by pilotchute** [comment]
1) I think that ground truth could be either stored in this repo, under an `ncl` folder, or in another github repo `geocat-ncl?`. Personally, I think that having it stored here in the geocat-f2py repo where the tests are stored as well, would be a good thing for simplicity, though running the NCL code may be non-trivial at times.

2) I think that having NCL code that generates `ground truth` for the unit tests would be a great idea. As far as generating input data, it is possible to define the `seed` for NCL's pseudo-random number generator such that we can repeatably generate large datasets easily. I don't think that implementing a helper function flexible enough to generate the variety of data we need is worth it over the very small amount of boilerplate that would be needed to generate NCL function specific test data.

**Comment by pilotchute** [comment]
- [ ] We will store NCL ground truth generation in `geocat-f2py/test/ncl`
